# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the IPQ ESS driver
#

obj-$(CONFIG_QCOM_IPQ4019_ESS_EDMA) += ipq_ess.o

ipq_ess-objs := ipq4019_swport.o ipq4019_phylink.o ipq4019_switch.o ipq4019_swmaster.o
