# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the IPQ ESS driver
#

obj-$(CONFIG_QCOM_IPQ4019_ESS) += ipqess.o

ipqess-objs := ipqess_port.o ipqess_phylink.o ipqess_switch.o ipqess_notifiers.o ipqess_edma.o
